### ISSUE TITLE
Allow injection of Enum/EnumValues

### ISSUE THREAD

**Issue by dpeek** [massiveinteractive/minject#13]

**Comment by dpeek** [comment]
Take a look at the version 2 PR and let me know what you think :)

**Comment by jasononeil** [comment]
Oh thanks... I didn't think you'd go for the "break compatibility a little bit by using macros option", but looks good.  I'll try play with it soon...

**Comment by dpeek** [comment]
I think it's about time for v2 – there's a bunch of other cleanup and optimisation in there as well. Speak now or hold your peace until v3 :)
