### ISSUE TITLE
Exception is not thrown b/c it throws exception when constructing

### ISSUE THREAD

**Issue by jozefchutka** [massiveinteractive/minject#27]
following line https://github.com/massiveinteractive/minject/blob/master/src/minject/point/PropertyInjectionPoint.hx#L48 is translated into javascript:
```
if(injection == null) throw "Injector is missing a rule to handle injection into property \"" + this.name + "\" " + ("of object \"" + Std.string(target) + "\". Target dependency: \"" + this.type + "\", named \"" + this.injectionName + "\"");
```

In case Std.string() throws error itself then the origin exception is not fired and is hard to trace. It was a case of missing command mapping in our case

**Comment by dpeek** [comment]
This should be fixed now (sorry, forgot to update the issue).

We're now printing target name, which is a the class name of the injection target (which cannot be null)
https://github.com/massiveinteractive/minject/blob/master/src/minject/point/PropertyInjectionPoint.hx#L49
