### ISSUE TITLE
CPP attendToInjectees leaks

### ISSUE THREAD

**Issue by thomasuster** [massiveinteractive/minject#30]
Because ObjectMaps do not use weak references and CPP has no weakmap(https://github.com/HaxeFoundation/haxe/issues/3200) minject leaks for all objects injected or instantiated in CPP. I was able to verify this in GlowCode, a memory profiler for windows.

The ObjectMap is used in attendToInjectees. I'd prefer removing it altogether as I never run into the defensive use-case I think it was intended for. Or maybe you'd prefer a removal/exception for CPP? If you want removal for CPP only I have a branch ready.

**Comment by thomasuster** [comment]
bump

**Comment by dpeek** [comment]
Sorry for the delay again, this one required some thought. After some digging I tend to agree with you, the only thing this map seems to do is prevent people from shooting themselves in the foot by using injectInto on the same instance multiple times. I'll remove it on a branch and see if I can find any edge cases in out projects.

Here's my notes from the dig:
- attendedToInjectees prevents injectInto from injecting into the same object twice
- if someone calls injectInto multiple times on the same instance, Not Our Problem (TM)
- only minject places it is called are:
	- InjectSingletonResult.getResponse: not a problem as only called when response is first created
	- Injector.instantiate: which is pretty much the same (create, inject)
- mmvc uses injectInto in ViewMap.injectInto, which guards against re-injecting already

**Comment by dpeek** [comment]
PR here: https://github.com/massiveinteractive/minject/pull/31

**Comment by thomasuster** [comment]
Awesome! I'll double check PR on Pakka Pets and see if I find anything.
