### ISSUE TITLE
V2 Migration: Map values by reference

### ISSUE THREAD

**Issue by thomasuster** [massiveinteractive/minject#37]
Since V2 uses macros if you were to call Injector methods indirectly the following no longer works.

```
var type:Class<Dynamic> = Class1;
injector.mapValue(type, null);
```

Or alternatively

```
var mapper:MyMapper = new MyMapper();
mapper.mapValue(Class1, new Class1());
```

**Comment by thomasuster** [comment]
All of my types to map are known at compile time, so I should be able to change all of the function headers to macros. Currently running into this problem...
```
You cannot access the flash package while in a macro (for flash.net.SharedObject)
```

**Comment by thomasuster** [comment]
I can't test V2 on Pakka Pets because of this openlf specific problem that I don't want to spend the time on to try and fix right now, but since it's project specific i'll go ahead and close this issue. New users may be a little confused that they can't do this though if they have any kind of a wrapper, but I'll leave it to you judgement whether or not that matters.

**Comment by jasononeil** [comment]
Yeah I had to rewrite my wrapper as a macro.  

Alternatively you can write your wrapper using `mapTypeValue` instead of `mapValue`, and get the class name yourself.  This has a couple of disadvantages: it does not apply `@:keep` metadata, and it will only work with classes, not abstracts such as `Int`.

**Comment by dpeek** [comment]
Re-opening this so that I mention it in the migration guide.

**Comment by dpeek** [comment]
On second thoughts, we can support this pretty easily. If we can't figure out a typename with the macro, we try to figure it out at runtime.

Only problem is our overloading of String for type + type params, meaning this currently won't work for Strings. Perhaps we could create a single-use-enum for that purpose, ie.

```haxe
injector.mapValue(TypeName('Array<String>', [])
```

cc/ @jasononeil

**Comment by thomasuster** [comment]
I'd rather convert over my wrappers, I only have three. If the wrappers just work without migration then don't they either A) loose performance boost or B) run a different abnormal code path?

**Comment by jasononeil** [comment]
@dpeek I'm not sure I understand the implementation you're going for, but I like the idea of a runtime fallback.  Now's the time to experiment and see if it's a good approach.  :+1:

**Comment by jasononeil** [comment]
I think this issue has been resolved in the current v2 branch by using `mapRuntimeTypeOf()`.
An example might be:

    var type:Class<Dynamic> = Class1;
    var val:Class1 = new Class 1();
    injector.mapRuntimeTypeOf( type ).toValue( val );

or even

    var val:Class1 = new Class 1();
    injector.mapRuntimeTypeOf( val ).toValue( val );

See https://github.com/massiveinteractive/minject/blob/v2/src/lib/minject/Injector.hx#L95

It would still be a handy thing to mention in the migration guide as this is the closest method to the old behaviour.
