### ISSUE TITLE
(v2) No easy way to use `injector.getInstance( Int )`

### ISSUE THREAD

**Issue by jasononeil** [massiveinteractive/minject#40]
Because `getInstance()` will instantiate an instance if it doesn't have an existing value, it doesn't make sense for non-class values that we have rules for.

The current workaround I have is:

```
if ( context.injector.hasRule(Int,"sessionExpiry") )
	expiry = context.injector.getRule( Int, "sessionExpiry" ).getResponse(null);
```

Which isn't too bad.  It would be nice if the parameter for `getResponse()` was optional though, as it already has a sensible fallback when the parameter is null.

If you want a more complete solution, an alternative might be:

```
injector.getValue( Int, "sessionExpiry" );
```

Which would search for a mapped value, but and either return null (or throw an error) if no value exists, rather than attempting to instantiate a class.

**Comment by jasononeil** [comment]
Fixed by https://github.com/massiveinteractive/minject/commit/e45ae45275452abbd15cbbc9cacfeb45e81b901e assuming we ever merge. And if we don't the issue's not valid anyway :)

**Comment by dpeek** [comment]
Happy to add finishing touches and merge/release v2, was waiting on any feedback from ufront :)

**Comment by jasononeil** [comment]
Yeah sorry for the delay, I really underestimated how long it would take to
get back on board after moving states. But I'm here now!

I'll try get you at least some feedback tomorrow :)
