### ISSUE TITLE
(v2) Follow type for anonymous structure

### ISSUE THREAD

**Issue by alebianco** [massiveinteractive/minject#45]
I'm having some issues mapping typedefs that define an anonymous structure, like ```typedef UAProvider = { var userAgent:String }``` because of a compilation error when calling ```Context.typeof(expr)```.

I'm trying to fix it to support anonymous structures but i noticed a commend in the followType method that explicitly avoids to try to resolve the TAnonymous type.

What's the rationale behind that? Is there a reason why that is disallowed? The mapping syntax would be much easier and maintainable if i could say ```injector.map(MyAnonTypeDef)``` instead of manually writing a string that describes the fields.

**Comment by dpeek** [comment]
That followType method was created to avoid this problem actually. Before Context.follow would resolve the anon type (ie. the fields). The new implementation should stop if the reference type is anonymous (so it should map 'UAProvider).

Since the same method is used both for generating the type info and when mapping you should you should end up with the same string.

I've been meaning to add a debugging mode where we log all the resolved type identifiers at compile time (both for injections and maps) so that you can see if there is anything unexpected. In the meantime can you add some logging and find out what is being resolved? (both in map and @inject)

**Comment by dpeek** [comment]
Can you provide a small failing example?

**Comment by alebianco** [comment]
yes it stops at UAProvider but that then fails when resolving the mappings at runtime.
I can add a test for that case, which will fail, is that ok?

**Comment by dpeek** [comment]
Are you mapping directly or by reference?

```
// reference
var ua:UAProvider = {...}
injector.map(ua, {...});

// directly
injector.map(UAProvider, {...});
```

A test case would be great.

**Comment by alebianco** [comment]
I found out that the mapping of typedefs changed a bit and it's not as un-maintainable as it was a couple of weeks ago, still have to do it by string tho.
I added three tests to show what works and what doesn't ... i'll keep looking for ways to make the preferable syntax work ...

**Comment by dpeek** [comment]
So, like `Array<Int>` a typedef identifier by itself is not actually valid Haxe syntax, which is where the error is coming from.

I've added some new methods to help with this:

```
var value:AnonType = {};
injector.mapTypeOf(value).toValue(value);
// generates injector.mapType('AnonType').toValue(value);

// and short hand

injector.injectValue(value);
// generates injector.mapType('AnonType').toValue(value);
```

Looking for a better name for that second method...

**Comment by alebianco** [comment]
I appreciate the ability to map a concrete type (i guess that would work also on non-anonymous types)
but that doesn't really help my case, where i'm using the typedef to describe a implementation of classes that don't implement the same interface.
So i basically won't have an instance of the typedef at "mapping time" ... guess i'll have to live with the string definitions

**Comment by dpeek** [comment]
There's not a huge difference between `map(TypeDef)` and `map('TypeDef')` in the end, I know it's a work around but there's not much we can do. @jasononeil suggested something like `map((o:TypeDef))` but I'm not sure that's any better.

**Comment by alebianco** [comment]
actually it might
the map('typedef') is misleading because the package will have to be included as well, which is verbose
not having a instance of the actual typedef could be useful to say map((o:typedef)) to sort-of cast it to the expected structure
