### ISSUE TITLE
Feature request: optional property injection points

### ISSUE THREAD

**Issue by jasononeil** [massiveinteractive/minject#50]
Allow an optional `PropertyInjectionPoint`.

Similar to how method injection points allow optional parameters to be skipped, check if a variable is `Null<T>`^, mark it as optional in the RTTI, and if there is no result, don't throw an error when applying the injection.

^ If this isn't explicit enough, perhaps some metadata?

**Comment by jasononeil** [comment]
I'm happy to provide a pull request for this, if you 

1. Think it's a good idea.
2. Specify if you'd prefer to base it on explicit `Null<T>` type hints or `@:optional` metadata etc.

**Comment by dpeek** [comment]
:+1: `Null<T>`

**Comment by alebianco** [comment]
I came asking for this. I like the Null<T> idea. I am happy dev.

**Comment by fantoine** [comment]
Any progress on this issue?
I also have this kind of issue when trying to inject a nullable value.

**Comment by fantoine** [comment]
An other solution could be to add some specific compiler define to allow nullable values on "debug".
