### ISSUE TITLE
haxelib install

### ISSUE THREAD

**Issue by alebianco** [massiveinteractive/minject#52]
The rc.1 release in haxelib can't be used because it does not recognise the imported classes when compiling.
Maybe release a working rc.2?

**Comment by dpeek** [comment]
I'm not sure what "does not recognise the imported classes" means...

**Comment by alebianco** [comment]
it was complaining that `Type not found : minject.Injector` but nevermind, i noticed there was a dev version installed so the rc1 was ignored. seems to be allright, sorry for the false alarm
